### ISSUE TITLE
Radio buttons seem to not work

### ISSUE THREAD

**Issue by bmaddy** [bilus/reagent-reforms#1]
With code like this:

``` clojure
(f/form
  (f/radio "data" app-state [:current-view])
  (f/radio "groups" app-state [:current-view]))
```

I expected to see a form that looks like this:
![good](https://cloud.githubusercontent.com/assets/74879/10784842/43eee64a-7d2e-11e5-99bd-9f8952845bd5.jpg)
it actually creates something like this:
![bad](https://cloud.githubusercontent.com/assets/74879/10784855/5a1219e2-7d2e-11e5-9f14-2568971fb859.jpg)
To get the form that looks the way I want, I have to change the code to use a different key, but then selecting the different buttons won't update the same piece of data:

``` clojure
(f/form
  (f/radio "data" app-state [:current-view])
  (f/radio "groups" app-state [:different]))
```

**Comment by bilus** [comment]
Thanks for letting me know about this. In my overzealousness to fix warnings about duplicate key I messed this up. I'm pushing a version that fixes the problem in a couple of minutes.

As a side note, using a radio requires you to provide a value for it like this:

``` clojure
(f/form
  (f/radio "data" app-state [:current-view] :data)
  (f/radio "groups" app-state [:current-view] :groups))
```

Keep tuned in, I'll post a comment after I push and deploy to clojars.

**Comment by bilus** [comment]
Pushed! I'm closing this for now. Please let me know if there are any problems.

**Comment by bmaddy** [comment]
Once I upgraded and did a `lein clean` everything started working great--thanks for the fix! I just started using reforms and am really enjoying it--thanks for making it!
